fix: Fix all old golintci-lint errors, add check for un-generated files, regened all proto/rest files for SDKs (#4457)
* initial commit

* add proto checks

* fix

* address comments

* update ruby bindings

* fix up

* regenerate python

* add missing files

* eurgh another fix

* oof fix ruby

* regen typescript stuff

* run pre-commit for ruby before diff

diff --git a/.github/workflows/sdk-python.yml b/.github/workflows/sdk-python.yml
--- a/.github/workflows/sdk-python.yml
+++ b/.github/workflows/sdk-python.yml
@@ -55,6 +55,25 @@ jobs:
       - name: Run Pydoclint
         run: poetry run pydoclint .
 
+      - name: Setup Go
+        if: matrix.python-version == '3.14'
+        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
+        with:
+          go-version: "1.26"
+
+      - name: Generate protobuf & REST client bindings
+        if: matrix.python-version == '3.14'
+        run: ./generate.sh
+
+      - name: Check generated bindings are up to date
+        if: matrix.python-version == '3.14'
+        run: |
+          git add -A hatchet_sdk/contracts hatchet_sdk/clients/rest
+          if ! git diff --cached --exit-code -- hatchet_sdk/contracts hatchet_sdk/clients/rest; then
+            echo "::error::Generated protobuf/REST bindings are out of date. Run 'sdks/python/generate.sh' and commit the changes."
+            exit 1
+          fi
+
       - name: Test install
         run: pip install -e .
 
